# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_feature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_feature.proto',
  package='image_feature',
  serialized_pb=_b('\n\x13image_feature.proto\x12\rimage_feature\"\xa5\x01\n\x08KeyPoint\x12\r\n\x05\x61ngle\x18\x01 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\x0e\n\x06octave\x18\x03 \x01(\x05\x12)\n\x02pt\x18\x06 \x01(\x0b\x32\x1d.image_feature.KeyPoint.point\x12\x10\n\x08response\x18\x04 \x01(\x02\x12\x0c\n\x04size\x18\x05 \x01(\x02\x1a\x1d\n\x05point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"h\n\x0b\x44\x65scriptors\x12-\n\x03\x64im\x18\x01 \x01(\x0b\x32 .image_feature.Descriptors.shape\x12\x13\n\x07\x65lement\x18\x02 \x03(\x02\x42\x02\x10\x01\x1a\x15\n\x05shape\x12\x0c\n\x04\x65lem\x18\x01 \x03(\x05\"i\n\nOneFeature\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x03kps\x18\x02 \x03(\x0b\x32\x17.image_feature.KeyPoint\x12\'\n\x03\x64\x65s\x18\x03 \x01(\x0b\x32\x1a.image_feature.Descriptors\"C\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x07\x66\x65\x61ture\x18\x02 \x03(\x0b\x32\x19.image_feature.OneFeature\"(\n\nStringDict\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"8\n\x08PathDict\x12,\n\tpath_dict\x18\x01 \x03(\x0b\x32\x19.image_feature.StringDict')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_KEYPOINT_POINT = _descriptor.Descriptor(
  name='point',
  full_name='image_feature.KeyPoint.point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='image_feature.KeyPoint.point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='image_feature.KeyPoint.point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=204,
)

_KEYPOINT = _descriptor.Descriptor(
  name='KeyPoint',
  full_name='image_feature.KeyPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='image_feature.KeyPoint.angle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='image_feature.KeyPoint.class_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='octave', full_name='image_feature.KeyPoint.octave', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pt', full_name='image_feature.KeyPoint.pt', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='image_feature.KeyPoint.response', index=4,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='image_feature.KeyPoint.size', index=5,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_KEYPOINT_POINT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=204,
)


_DESCRIPTORS_SHAPE = _descriptor.Descriptor(
  name='shape',
  full_name='image_feature.Descriptors.shape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elem', full_name='image_feature.Descriptors.shape.elem', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=310,
)

_DESCRIPTORS = _descriptor.Descriptor(
  name='Descriptors',
  full_name='image_feature.Descriptors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dim', full_name='image_feature.Descriptors.dim', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='element', full_name='image_feature.Descriptors.element', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[_DESCRIPTORS_SHAPE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=310,
)


_ONEFEATURE = _descriptor.Descriptor(
  name='OneFeature',
  full_name='image_feature.OneFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='image_feature.OneFeature.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kps', full_name='image_feature.OneFeature.kps', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='des', full_name='image_feature.OneFeature.des', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=417,
)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='image_feature.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='image_feature.Feature.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature', full_name='image_feature.Feature.feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=486,
)


_STRINGDICT = _descriptor.Descriptor(
  name='StringDict',
  full_name='image_feature.StringDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='image_feature.StringDict.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='image_feature.StringDict.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=528,
)


_PATHDICT = _descriptor.Descriptor(
  name='PathDict',
  full_name='image_feature.PathDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path_dict', full_name='image_feature.PathDict.path_dict', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=586,
)

_KEYPOINT_POINT.containing_type = _KEYPOINT
_KEYPOINT.fields_by_name['pt'].message_type = _KEYPOINT_POINT
_DESCRIPTORS_SHAPE.containing_type = _DESCRIPTORS
_DESCRIPTORS.fields_by_name['dim'].message_type = _DESCRIPTORS_SHAPE
_ONEFEATURE.fields_by_name['kps'].message_type = _KEYPOINT
_ONEFEATURE.fields_by_name['des'].message_type = _DESCRIPTORS
_FEATURE.fields_by_name['feature'].message_type = _ONEFEATURE
_PATHDICT.fields_by_name['path_dict'].message_type = _STRINGDICT
DESCRIPTOR.message_types_by_name['KeyPoint'] = _KEYPOINT
DESCRIPTOR.message_types_by_name['Descriptors'] = _DESCRIPTORS
DESCRIPTOR.message_types_by_name['OneFeature'] = _ONEFEATURE
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['StringDict'] = _STRINGDICT
DESCRIPTOR.message_types_by_name['PathDict'] = _PATHDICT

KeyPoint = _reflection.GeneratedProtocolMessageType('KeyPoint', (_message.Message,), dict(

  point = _reflection.GeneratedProtocolMessageType('point', (_message.Message,), dict(
    DESCRIPTOR = _KEYPOINT_POINT,
    __module__ = 'image_feature_pb2'
    # @@protoc_insertion_point(class_scope:image_feature.KeyPoint.point)
    ))
  ,
  DESCRIPTOR = _KEYPOINT,
  __module__ = 'image_feature_pb2'
  # @@protoc_insertion_point(class_scope:image_feature.KeyPoint)
  ))
_sym_db.RegisterMessage(KeyPoint)
_sym_db.RegisterMessage(KeyPoint.point)

Descriptors = _reflection.GeneratedProtocolMessageType('Descriptors', (_message.Message,), dict(

  shape = _reflection.GeneratedProtocolMessageType('shape', (_message.Message,), dict(
    DESCRIPTOR = _DESCRIPTORS_SHAPE,
    __module__ = 'image_feature_pb2'
    # @@protoc_insertion_point(class_scope:image_feature.Descriptors.shape)
    ))
  ,
  DESCRIPTOR = _DESCRIPTORS,
  __module__ = 'image_feature_pb2'
  # @@protoc_insertion_point(class_scope:image_feature.Descriptors)
  ))
_sym_db.RegisterMessage(Descriptors)
_sym_db.RegisterMessage(Descriptors.shape)

OneFeature = _reflection.GeneratedProtocolMessageType('OneFeature', (_message.Message,), dict(
  DESCRIPTOR = _ONEFEATURE,
  __module__ = 'image_feature_pb2'
  # @@protoc_insertion_point(class_scope:image_feature.OneFeature)
  ))
_sym_db.RegisterMessage(OneFeature)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), dict(
  DESCRIPTOR = _FEATURE,
  __module__ = 'image_feature_pb2'
  # @@protoc_insertion_point(class_scope:image_feature.Feature)
  ))
_sym_db.RegisterMessage(Feature)

StringDict = _reflection.GeneratedProtocolMessageType('StringDict', (_message.Message,), dict(
  DESCRIPTOR = _STRINGDICT,
  __module__ = 'image_feature_pb2'
  # @@protoc_insertion_point(class_scope:image_feature.StringDict)
  ))
_sym_db.RegisterMessage(StringDict)

PathDict = _reflection.GeneratedProtocolMessageType('PathDict', (_message.Message,), dict(
  DESCRIPTOR = _PATHDICT,
  __module__ = 'image_feature_pb2'
  # @@protoc_insertion_point(class_scope:image_feature.PathDict)
  ))
_sym_db.RegisterMessage(PathDict)


_DESCRIPTORS.fields_by_name['element'].has_options = True
_DESCRIPTORS.fields_by_name['element']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
